### ISSUE TITLE
Item pickup not working

### ISSUE THREAD

**Issue by nitoygo** [MUnique/OpenMU#120]
I tried hard coding the DefaultDropGenerator to always drop a specific type (e.g. Excellent), it worked, but, I can't pick it up.

I tried dropping some items from my inventory and I can't pick them up too.

I will try to investigate this tomorrow. If you can guide me where to look, or you already have an idea, I'd appreciate it.

**Comment by sven-n** [comment]
I couldn’t reproduce the issue. Did you close it because it works for you now, too?

**Comment by nitoygo** [comment]
> Did you close it because it works for you now, too?
I closed it because I'm not so sure if this report is valid.
This was what I did:
```C#
        public IEnumerable<Item> GetItemDropsOrAddMoney(MonsterDefinition monster, int gainedExperience, Player player)
        {
            ...
            yield return this.GetRandomExcellentItem((int)monster[Stats.Level]);
            /*
            for (int i = 0; i < monster.NumberOfMaximumItemDrops; i++)
```

I got the following exception:
```
[ERROR] 2019-05-28 00:09:45,095 [MUnique.OpenMU.GameServer.RemoteView.RemotePlayer] [1] - System.ArgumentException: The item needs to be of type MUnique.OpenMU.Persistence.EntityFramework.Item.
Parameter name: item
   at MUnique.OpenMU.Persistence.CollectionAdapter`2.Add(TClass item) in D:\Mu\MU_S6\server\src\Persistence\CollectionAdapter.cs:line 71
   at MUnique.OpenMU.GameLogic.ItemStorageAdapter.CollectionAdapter.Add(Item item) in D:\Mu\MU_S6\server\src\GameLogic\ItemStorageAdapter.cs:line 78
   at MUnique.OpenMU.GameLogic.Storage.AddItem(Byte slot, Item item) in D:\Mu\MU_S6\server\src\GameLogic\Storage.cs:line 107
   at MUnique.OpenMU.GameLogic.InventoryStorage.AddItem(Byte slot, Item item) in D:\Mu\MU_S6\server\src\GameLogic\InventoryStorage.cs:line 73
   at MUnique.OpenMU.GameLogic.DroppedItem.TryPickUp(Player player) in D:\Mu\MU_S6\server\src\GameLogic\DroppedItem.cs:line 158
   at MUnique.OpenMU.GameLogic.DroppedItem.TryPickUpBy(Player player, Item& stackTarget) in D:\Mu\MU_S6\server\src\GameLogic\DroppedItem.cs:line 100
   at MUnique.OpenMU.GameLogic.PlayerActions.Items.PickupItemAction.TryPickupItem(Player player, DroppedItem droppedItem, Item& stackTarget) in D:\Mu\MU_S6\server\src\GameLogic\PlayerActions\Items\PickupItemAction.cs:line 67
   at MUnique.OpenMU.GameLogic.PlayerActions.Items.PickupItemAction.PickupItem(Player player, UInt16 dropId) in D:\Mu\MU_S6\server\src\GameLogic\PlayerActions\Items\PickupItemAction.cs:line 29
   at MUnique.OpenMU.GameServer.MessageHandler.Items.PickupItemHandlerPlugIn.HandlePacket(Player player, Span`1 packet) in D:\Mu\MU_S6\server\src\GameServer\MessageHandler\Items\PickupItemHandlerPlugIn.cs:line 36
   at MUnique.OpenMU.GameServer.MessageHandler.PacketHandlerPlugInContainer`1.HandlePacket(Player player, Span`1& packet, THandler handler) in D:\Mu\MU_S6\server\src\GameServer\MessageHandler\PacketHandlerPlugInContainer.cs:line 96
   at MUnique.OpenMU.GameServer.MessageHandler.PacketHandlerPlugInContainer`1.HandlePacket(RemotePlayer player, Span`1& packet) in D:\Mu\MU_S6\server\src\GameServer\MessageHandler\PacketHandlerPlugInContainer.cs:line 73
   at MUnique.OpenMU.GameServer.RemoteView.RemotePlayer.PacketReceived(ReadOnlySequence`1 sequence) in D:\Mu\MU_S6\server\src\GameServer\RemoteView\RemotePlayer.cs:line 144
```

I hard-coded the item return since monsters don't drop any items in my env.
