### ISSUE TITLE
[Npgsql.NpgsqlConnector] [(null)] - Breaking connector

### ISSUE THREAD

**Issue by Cedyk** [MUnique/OpenMU#144]
Hello, after some complications I managed to compile and run the server. But when creating the database, I encounter a problem. The database is not created.
I tried to run MUnique.OpenMU.Startup.exe with the "-reinit" parameter to arm the database automatically, but I get the following error:

`
[INFO ] 2020-01-08 13:31:14,352 [MUnique.OpenMU.Startup.Program] [(null)] - The database is getting (re-)initialized...

[ERROR] 2020-01-08 13:31:16,099 [Npgsql.NpgsqlConnector] [(null)] - Breaking connector

[ERROR] 2020-01-08 13:31:16,242 [Npgsql.NpgsqlConnector] [(null)] - Breaking connector

[INFO ] 2020-01-08 13:32:02,488 [MUnique.OpenMU.Startup.Program] [(null)] - ...initialization finished.

[INFO ] 2020-01-08 13:32:02,853 [MUnique.OpenMU.Startup.Program] [(null)] - Start initializing sub-components

[INFO ] 2020-01-08 13:32:03,724 [MUnique.OpenMU.Startup.Program] [(null)] - Start initializing game servers

[INFO ] 2020-01-08 13:32:07,415 [MUnique.OpenMU.Startup.Program] [1] - Game Server 1 - [Server 1] initialized

[INFO ] 2020-01-08 13:32:07,442 [MUnique.OpenMU.Startup.Program] [0] - Game Server 0 - [Server 0] initialized

[INFO ] 2020-01-08 13:32:07,462 [MUnique.OpenMU.Startup.Program] [2] - Game Server 2 - [Server 2] initialized

[INFO ] 2020-01-08 13:32:07,472 [MUnique.OpenMU.Startup.Program] [(null)] - All game servers initialized, elapsed time: 00:00:03.7372135

[INFO ] 2020-01-08 13:32:07,481 [MUnique.OpenMU.Startup.Program] [(null)] - Start initializing admin panel for port 1234.

[INFO ] 2020-01-08 13:32:07,830 [MUnique.OpenMU.Startup.Program] [(null)] - Admin panel initialized, port 1234.`

Maybe, someone could provide me with a backup of the database structure to import in my postgressql, or report the problem in case nobody has happened. Thank you.

**Comment by sven-n** [comment]
Hi, I can only guess at the moment but I think it’s a connection issue. First, you need to make sure that the server is reachable. By default, only connections from the same host are accepted by Postgres. Then you need to make sure that the connection strings are correct in the ConnectionSettings.xml.

**Comment by sven-n** [comment]
Hi, any success yet?
I have another idea which could help to find the problem - you could activate the logging in the MUnique.OpenMU.Startup.exe.log4net.xml. There are two loggers for Npgsql, which you can set to DEBUG, for example.

**Comment by Cedyk** [comment]
Hi, thanks for the help. I am really confused, the tables were created. Therefore I can assume that the connection is correct. But the data (Characters, items, etc.) are not saved in the database.
I found the configuration file MUnique.OpenMU.Startup.exe.log4net.xml, I tried to enable debug, but it wouldn't work either. Also, the sql.log file is empty

```
log4net:ERROR Undefined level [ON] on Logger [Npgsql.NpgsqlCommand].
log4net:ERROR Undefined level [ON] on Logger [Npgsql.NpgsqlConnection].
log4net:ERROR Undefined level [ON] on Logger [MUnique.OpenMU.Network.Connection].

log4net:ERROR Undefined level [On] on Logger [Npgsql.NpgsqlCommand].
log4net:ERROR Undefined level [On] on Logger [Npgsql.NpgsqlConnection].
log4net:ERROR Undefined level [On] on Logger [MUnique.OpenMU.Network.Connection].

log4net:ERROR Undefined level [True] on Logger [Npgsql.NpgsqlCommand].
log4net:ERROR Undefined level [True] on Logger [Npgsql.NpgsqlConnection].
log4net:ERROR Undefined level [True] on Logger [MUnique.OpenMU.Network.Connection].

log4net:ERROR Undefined level [TRUE] on Logger [Npgsql.NpgsqlCommand].
log4net:ERROR Undefined level [TRUE] on Logger [Npgsql.NpgsqlConnection].
log4net:ERROR Undefined level [TRUE] on Logger [MUnique.OpenMU.Network.Connection].

log4net:ERROR Undefined level [true] on Logger [Npgsql.NpgsqlCommand].
log4net:ERROR Undefined level [true] on Logger [Npgsql.NpgsqlConnection].
log4net:ERROR Undefined level [true] on Logger [MUnique.OpenMU.Network.Connection].
```

**Comment by sven-n** [comment]
Okay, I think you entered „true“ or „on“ at the level in the log4net config xml file. Instead, please try „DEBUG“.

**Comment by Cedyk** [comment]
I managed to put the DEBUG, it was a bad interpretation of mine, since I already apologize. Now that I have the record, I could find some things a little deeper.
When creating a character, I get the following exceptions:

```
[ERROR] 2020-01-12 16:30:12,477 [MUnique.OpenMU.Network.Connection] [(null)] - Connection will be disconnected, because of an exception
Pipelines.Sockets.Unofficial.ConnectionResetException: Se ha forzado la interrupción de una conexión existente por el host remoto.
 ---> System.Net.Sockets.SocketException (10054): Se ha forzado la interrupción de una conexión existente por el host remoto.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\Internal\Throw.cs:line 59
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|10_0(SocketError e) in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketAwaitableEventArgs.cs:line 87
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketAwaitableEventArgs.cs:line 82
   at Pipelines.Sockets.Unofficial.SocketConnection.DoReceiveAsync() in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketConnection.Receive.cs:line 64
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadBuffer()
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadSource() in C:\Users\rolda\Desktop\OpenMU-master\src\Network\PacketPipeReaderBase.cs:line 48
[ERROR] 2020-01-12 16:30:12,477 [MUnique.OpenMU.Network.Connection] [(null)] - Connection will be disconnected, because of an exception
Pipelines.Sockets.Unofficial.ConnectionResetException: Se ha forzado la interrupción de una conexión existente por el host remoto.
 ---> System.Net.Sockets.SocketException (10054): Se ha forzado la interrupción de una conexión existente por el host remoto.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\Internal\Throw.cs:line 59
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|10_0(SocketError e) in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketAwaitableEventArgs.cs:line 87
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketAwaitableEventArgs.cs:line 82
   at Pipelines.Sockets.Unofficial.SocketConnection.DoReceiveAsync() in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketConnection.Receive.cs:line 64
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadBuffer()
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadSource() in C:\Users\rolda\Desktop\OpenMU-master\src\Network\PacketPipeReaderBase.cs:line 48
```

After this, the character within the mu client behaves well. There are no apparent errors. But when trying to place items (whatever: boots, helmet, weapons, etc). I can't do it even if I have the required stats.
So I went to the postgresql admin, I can notice that in data.StatsAttribute the "definition id" column this null, for the last character created. I suppose that having no stats creates a problem.
When I disconnect the character from the mu client, throw the following exception:

```
[ERROR] 2020-01-12 16:35:57,025 [MUnique.OpenMU.Network.Connection] [(null)] - Connection will be disconnected, because of an exception
Pipelines.Sockets.Unofficial.ConnectionAbortedException: The connection was aborted
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadBuffer()
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadSource() in C:\Users\rolda\Desktop\OpenMU-master\src\Network\PacketPipeReaderBase.cs:line 48
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadBuffer()
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadSource() in C:\Users\rolda\Desktop\OpenMU-master\src\Network\PacketPipeReaderBase.cs:line 48
[ERROR] 2020-01-12 16:35:57,088 [MUnique.OpenMU.Network.Connection] [(null)] - Connection will be disconnected, because of an exception
System.InvalidOperationException: Reading is not allowed after reader was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed)
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadBuffer() in C:\Users\rolda\Desktop\OpenMU-master\src\Network\PacketPipeReaderBase.cs:line 112
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadSource() in C:\Users\rolda\Desktop\OpenMU-master\src\Network\PacketPipeReaderBase.cs:line 48
```

And when trying to enter the client, with the same account and same character throws this exception and there is a black screen, indefinite:

```
[ERROR] 2020-01-12 16:37:45,603 [MUnique.OpenMU.Network.Connection] [(null)] - Connection will be disconnected, because of an exception
Pipelines.Sockets.Unofficial.ConnectionResetException: Se ha forzado la interrupción de una conexión existente por el host remoto.
 ---> System.Net.Sockets.SocketException (10054): Se ha forzado la interrupción de una conexión existente por el host remoto.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\Internal\Throw.cs:line 59
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketAwaitableEventArgs.cs:line 74
   at Pipelines.Sockets.Unofficial.SocketConnection.DoReceiveAsync() in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketConnection.Receive.cs:line 64
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadBuffer()
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadSource() in C:\Users\rolda\Desktop\OpenMU-master\src\Network\PacketPipeReaderBase.cs:line 48
[ERROR] 2020-01-12 16:37:45,603 [MUnique.OpenMU.Network.Connection] [(null)] - Connection will be disconnected, because of an exception
Pipelines.Sockets.Unofficial.ConnectionResetException: Se ha forzado la interrupción de una conexión existente por el host remoto.
 ---> System.Net.Sockets.SocketException (10054): Se ha forzado la interrupción de una conexión existente por el host remoto.
   at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\Internal\Throw.cs:line 59
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketAwaitableEventArgs.cs:line 74
   at Pipelines.Sockets.Unofficial.SocketConnection.DoReceiveAsync() in C:\Code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketConnection.Receive.cs:line 64
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadBuffer()
   at MUnique.OpenMU.Network.PacketPipeReaderBase.ReadSource() in C:\Users\rolda\Desktop\OpenMU-master\src\Network\PacketPipeReaderBase.cs:line 48
[ERROR] 2020-01-12 16:37:56,542 [MUnique.OpenMU.GameServer.RemoteView.RemotePlayer] [0] - System.ArgumentException: An item with the same key has already been added. Key:
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at MUnique.OpenMU.AttributeSystem.AttributeSystem..ctor(IEnumerable`1 statAttributes, IEnumerable`1 baseAttributes, IEnumerable`1 attributeRelationships) in C:\Users\rolda\Desktop\OpenMU-master\src\AttributeSystem\AttributeSystem.cs:line 28
   at MUnique.OpenMU.GameLogic.Attributes.ItemAwareAttributeSystem..ctor(Character character) in C:\Users\rolda\Desktop\OpenMU-master\src\GameLogic\Attributes\ItemAwareAttributeSystem.cs:line 23
   at MUnique.OpenMU.GameLogic.Player.OnPlayerEnteredWorld(Object sender, EventArgs e) in C:\Users\rolda\Desktop\OpenMU-master\src\GameLogic\Player.cs:line 932
   at MUnique.OpenMU.GameLogic.Player.set_SelectedCharacter(Character value) in C:\Users\rolda\Desktop\OpenMU-master\src\GameLogic\Player.cs:line 145
   at MUnique.OpenMU.GameLogic.PlayerActions.Character.SelectCharacterAction.SelectCharacter(Player player, String characterName) in C:\Users\rolda\Desktop\OpenMU-master\src\GameLogic\PlayerActions\Character\SelectCharacterAction.cs:line 32
   at MUnique.OpenMU.GameServer.MessageHandler.Character.CharacterSelectPacketHandlerPlugIn.HandlePacket(Player player, Span`1 packet) in C:\Users\rolda\Desktop\OpenMU-master\src\GameServer\MessageHandler\Character\CharacterSelectPacketHandlerPlugIn.cs:line 35
   at MUnique.OpenMU.GameServer.MessageHandler.PacketHandlerPlugInContainer`1.HandlePacket(Player player, Span`1& packet, THandler handler) in C:\Users\rolda\Desktop\OpenMU-master\src\GameServer\MessageHandler\PacketHandlerPlugInContainer.cs:line 83
   at MUnique.OpenMU.GameServer.MessageHandler.GroupPacketHandlerPlugIn.HandlePacket(Player player, Span`1 packet) in C:\Users\rolda\Desktop\OpenMU-master\src\GameServer\MessageHandler\GroupPacketHandlerPlugIn.cs:line 37
   at MUnique.OpenMU.GameServer.MessageHandler.PacketHandlerPlugInContainer`1.HandlePacket(Player player, Span`1& packet, THandler handler) in C:\Users\rolda\Desktop\OpenMU-master\src\GameServer\MessageHandler\PacketHandlerPlugInContainer.cs:line 83
   at MUnique.OpenMU.GameServer.RemoteView.RemotePlayer.PacketReceived(ReadOnlySequence`1 sequence) in C:\Users\rolda\Desktop\OpenMU-master\src\GameServer\RemoteView\RemotePlayer.cs:line 156
```

PD 1: The database was created correctly, the tables and columns I see perfect. The settings, drop and monsters also look and work properly.
PD 2: Sorry for such a long issue, I try to make it work step by step. Any log or test that you think is prudent to do, let me know and I will try to replicate it.

**Comment by sven-n** [comment]
No problem, I’m trying my best to help you :)

You can ignore the ConnectionResetExceptions as they’re always occurring when a connection gets closed - e.g. this occurs when the game client closes the connection to the connect server after a game server was selected. I think the actual issue is logged in the last exception. I don’t know the exact reason yet, but according to the error there are missing IDs in the AttributeDefinitions. I‘ll try to reproduce the issue tomorrow, if I can somehow find the time.

**Comment by sven-n** [comment]
Unfortunately, I can't reproduce your issue :-( I tried it with the test accounts test3, test300 and test 400. I can select every character and get no error when entering the game.

  * Do you have any local changes?
  * Which account do you use for testing?

**Comment by sven-n** [comment]
Ah sorry, I think I understand the issue now. The error occurs for a in-game-created character. I already have an idea what could go wrong, too.

**Comment by Cedyk** [comment]
Hola, muy buen lunes, gracias por la rapidez. Utilizo el admin "http://localhost:1234/admin" para crear la cuenta nueva. Luego de eso, dentro del cliente ya conectado creo el personaje.

**Comment by sven-n** [comment]
Okay, I guess we have several issues here :-(

> After this, the character within the mu client behaves well. There are no apparent errors. But when trying to place items (whatever: boots, helmet, weapons, etc). I can't do it even if I have the required stats.

I tried it with buying some items from the NPC. I couldn't equip them as well. The Item.ItemSlot (ItemSlotType) did not have the corresponding item slot indexes in it's collection :-( -> First issue, not fixed yet

> And when trying to enter the client, with the same account and same character throws this exception and there is a black screen, indefinite:

-> Second issue, fixed :)

**Comment by sven-n** [comment]
@Cedyk I think I fixed the ItemSlots issue, but had no time to test it in-game. Can you try it with the newest commit?

Thanks @fos83 for the hint :)

**Comment by Cedyk** [comment]
I will recompile the files and test if it works correctly, then I give you the news, thank you very much!

**Comment by Cedyk** [comment]
I managed to recompile the project, and the items can now be equipped. Just as the character's progress is saved. Therefore the issue is resolved. Many thanks!.
I will continue testing, you will probably see new issues of my authorship. Greetings and more thanks!

**Comment by sven-n** [comment]
Hey, thank you very much, too. Unfortunately, I don’t have a lot of time to test complex stuff with the game client, so help is always welcome :)
