### ISSUE TITLE
Receiving error when build docker image

### ISSUE THREAD

**Issue by jasondavindev** [MUnique/OpenMU#189]
**Describe the bug**
I'm receiving a exception when I runs dockerized application.

**To Reproduce**
1. Changes `docker-compose.yml` to build project Dockerfile
2. Runs `docker-compose up --build`

**Expected behavior**
I expect the application will run normally

**Screenshots**
Error stack trace:
```
munique     | Unhandled exception. System.TypeInitializationException: The type initializer for 'MUnique.OpenMU.Persistence.EntityFramework.ConnectionConfigurator' threw an exception.
munique     |  ---> System.TypeLoadException: Could not load type 'MUnique.OpenMU.Persistence.EntityFramework.TypedContext' from assembly 'MUnique.OpenMU.Persistence.EntityFramework, Version=0.3.3.0, Culture=neutral, PublicKeyToken=null'.
munique     |    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
munique     |    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
munique     |    at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
munique     |    at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
munique     |    at MUnique.OpenMU.Persistence.EntityFramework.ConnectionConfigurator.LoadSettings() in /app/src/Persistence/EntityFramework/ConnectionConfigurator.cs:line 147
munique     |    at MUnique.OpenMU.Persistence.EntityFramework.ConnectionConfigurator..cctor() in /app/src/Persistence/EntityFramework/ConnectionConfigurator.cs:line 55
munique     |    --- End of inner exception stack trace ---
munique     |    at MUnique.OpenMU.Persistence.EntityFramework.ConnectionConfigurator.Configure(DbContext context, DbContextOptionsBuilder optionsBuilder) in /app/src/Persistence/EntityFramework/ConnectionConfigurator.cs:line 93
munique     |    at MUnique.OpenMU.Persistence.EntityFramework.EntityDataContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in /app/src/Persistence/EntityFramework/EntityDataContext.cs:line 27
munique     |    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
munique     |    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
munique     |    at Microsoft.EntityFrameworkCore.DbContext.get_Model()
munique     |    at MUnique.OpenMU.Persistence.EntityFramework.GenericRepositoryBase`1..ctor(RepositoryManager repositoryManager) in /app/src/Persistence/EntityFramework/GenericRepositoryBase.cs:line 33
munique     |    at MUnique.OpenMU.Persistence.EntityFramework.CachingGenericRepository`1..ctor(RepositoryManager repositoryManager) in /app/src/Persistence/EntityFramework/CachingGenericRepository.cs:line 27
munique     |    at MUnique.OpenMU.Persistence.EntityFramework.AccountRepository..ctor(CachingRepositoryManager repositoryManager) in /app/src/Persistence/EntityFramework/AccountRepository.cs:line 25
munique     |    at MUnique.OpenMU.Persistence.EntityFramework.CachingRepositoryManager.RegisterRepositories() in /app/src/Persistence/EntityFramework/CachingRepositoryManager.cs:line 26
munique     |    at MUnique.OpenMU.Persistence.EntityFramework.PersistenceContextProvider..ctor() in /app/src/Persistence/EntityFramework/PersistenceContextProvider.cs:line 23
munique     |    at MUnique.OpenMU.Startup.Program.PrepareRepositoryManager(Boolean reinit, Boolean autoupdate) in /app/src/Startup/Program.cs:line 214
munique     |    at MUnique.OpenMU.Startup.Program..ctor(String[] args) in /app/src/Startup/Program.cs:line 56
munique     |    at MUnique.OpenMU.Startup.Program.Main(String[] args) in /app/src/Startup/Program.cs:line 160
```

**Desktop:**
 - OS: Ubuntu 18.04

**Comment by sven-n** [comment]
```
munique     |  ---> System.TypeLoadException: Could not load type 'MUnique.OpenMU.Persistence.EntityFramework.TypedContext' from assembly 'MUnique.OpenMU.Persistence.EntityFramework, Version=0.3.3.0, Culture=neutral, PublicKeyToken=null'.
```

That's strange, because the type name must be ```MUnique.OpenMU.Persistence.EntityFramework.TypedContext`1```, which is defined in the ```ConnectionSettings.xml```.

**Comment by sven-n** [comment]
Can you try it again with the newest master?
I changed a few things to handle such a case.

**Comment by jasondavindev** [comment]
Oh yeah! Works, but the error has changed ;(

Now the error is because of the certificate

```bash
munique     | [FATAL] 2020-06-01 12:35:26,119 [Microsoft.AspNetCore.Server.Kestrel] [(null)] - Unable to start Kestrel.
munique     | System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
munique     | To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
munique     | For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
munique     |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
munique     |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
munique     |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
munique     |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
munique     |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
munique     | Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
munique     |    at MUnique.OpenMU.Startup.Program.Dispose() in /app/src/Startup/Program.cs:line 135
munique     |    at MUnique.OpenMU.Startup.Program.Main(String[] args) in /app/src/Startup/Program.cs:line 119
munique     |    at MUnique.OpenMU.Startup.Program.<Main>(String[] args)
```

The containers dies with 139 status code error.

I tried to generate the certificate, but without success. I receive an error when to try this https://stackoverflow.com/questions/55485511/how-to-run-dotnet-dev-certs-https-trust. Throws an error saying incorrect password, even setting the --password flag.

Can you help me? (It's my first contact with C#, .NET .. microsoft technologies)

**Comment by sven-n** [comment]
Ohh, sure but it‘ll take a while, I’m very busy these days :-/
The certificate is needed for the public api project, I think.

**Comment by jasondavindev** [comment]
Yes, is needed for the pubic api. Do you know where the certificate is saved?

**Comment by sven-n** [comment]
I have no idea, I‘d have to look it up ;)

**Comment by sven-n** [comment]
I found a guide here: https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-3.1

**Comment by jasondavindev** [comment]
Oooh thanks!!! Works
I will open a PR to create shell commands to generate the certificate.
