### ISSUE TITLE
Local Run - No Internet

### ISSUE THREAD

**Issue by DZ1M** [MUnique/OpenMU#387]
**Describe the bug**
Mu Server Local does not run if there is no Internet

Error:
```
2023-11-16 12:32:52 2023-11-16 15:32:52.669 +00:00 [Information] [MUnique.OpenMU.GameServer.DefaultTcpGameServerListener] Starting Server Listener, port 55901
2023-11-16 12:32:52 2023-11-16 15:32:52.720 +00:00 [Error] [MUnique.OpenMU.GameServer.GameServer] Could not start the server listeners: Name does not resolve (api.ipify.org:443)
2023-11-16 12:32:52 System.Net.Http.HttpRequestException: Name does not resolve (api.ipify.org:443)
2023-11-16 12:32:52  ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
2023-11-16 12:32:52    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2023-11-16 12:32:52    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2023-11-16 12:32:52    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
2023-11-16 12:32:52    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2023-11-16 12:32:52    --- End of inner exception stack trace ---
2023-11-16 12:32:52    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2023-11-16 12:32:52    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023-11-16 12:32:52    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023-11-16 12:32:52    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
2023-11-16 12:32:52    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
2023-11-16 12:32:52    at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
2023-11-16 12:32:52    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2023-11-16 12:32:52    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023-11-16 12:32:52    at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
2023-11-16 12:32:52    at MUnique.OpenMU.Network.PublicIpResolver.InternalGetIPv4Async() in /src/Network/PublicIpResolver.cs:line 50
2023-11-16 12:32:52    at MUnique.OpenMU.Network.PublicIpResolver.ResolveIPv4Async() in /src/Network/PublicIpResolver.cs:line 38
2023-11-16 12:32:52    at MUnique.OpenMU.Network.ConfigurableIpResolver.ResolveIPv4Async() in /src/Network/ConfigurableIpResolver.cs:line 43
2023-11-16 12:32:52    at MUnique.OpenMU.GameServer.DefaultTcpGameServerListener.StartAsync() in /src/GameServer/DefaultTcpGameServerListener.cs:line 90
2023-11-16 12:32:52    at MUnique.OpenMU.GameServer.GameServer.StartAsync() in /src/GameServer/GameServer.cs:line 154
```

**To Reproduce**
1. Go to 'Docker'
2. Click on 'Run'
3. Scroll down to 'Docker'

**Expected behavior**
Server Run on Local Machine on Internet or Not

**Screenshots**

![image](https://github.com/MUnique/OpenMU/assets/61568662/4bb2b381-ca2f-44d4-a573-0b7c0f350fb3)

**Comment by khaiodev** [comment]
It is not a bug, but rather some name resolution that you are unable to do.

Have you checked if your gateway can resolve this name?

**Comment by DZ1M** [comment]
> It is not a bug, but rather some name resolution that you are unable to do.
> 
> Have you checked if your gateway can resolve this name?

Yes bro, The problem occurs if no have network available to  Get in the 'api. ipify.org', example: I didn't pay the internet bill, so I won't be able to run the MU locally for testing, as I don't have internet.

**Comment by sven-n** [comment]
This error should not prevent the application from starting. It originates from the public ip resolver. So, if you don't want to make your server available to the internet, and just want to work locally, just set the IP Resolve setting in the admin panel (Game Configuration -> System) to Local or Loopback.
